### ISSUE TITLE
Question about lonlat

### ISSUE THREAD

**Issue by lixus7** [BIRD-TAO/CLCRN#1]
Congratulations for your AAAI 2022 work, i have met some bug when i run your code. There is something wrong in the dataset folder that your dataset lack of 'lonlat' part. Wish your regard, Thank you!

**Comment by EDAPINENUT** [comment]
We have re-uploaded the dataset in the google drive. The zip file needs to be unzipped, and there exists a file named 'position_info.pkl', where the 'lonlat' is contained in. If you have further problems, you can show us the bug leading to implementation failure. Thanks for your interest and advice.

**Comment by lixus7** [comment]
Thank you, I later found out that kernel_info.pkl is the file that after processing. Also, I'm going to replicate your work to other multivariate time series such as METRLA, electricity and some other datasets without location information. Then, unfortunately, the section 4.4 in your paper explains that your work is not applicable to traffic related work. Thanks and respect for your work as the only open source one of time series forecasting work in AAAI 2022. In the future, I will continue to read your paper carefully and try to see if it can be applied to other multivariate time series tasks as for your great job. Respect！Thank you！

**Comment by EDAPINENUT** [comment]
I am very sorry about the preprocessing file does not update in time, bringing you trouble. And the error will be soon improved.
In our method, the convolution is mainly based on continuous convolution, which is reasonable for weather forecasting, while the traffic signals are discrete. The other methods in the baselines folder can be implemented to traffic forecasting problems. For METRLA, the DCRNN's official github seems to provide the location information of every node, and we also conduct some experiments on METRLA: The performance is not better than DCRNN, but better than AGCRN. To be honest, most of the so-called SOTA works can not outperform DCRNN in METRLA, with MAE equalling about 3.14 in the pytorch version.

 If you are interested, you can conduct further experiments for METRLA. Thanks for your advice.
