### ISSUE TITLE
visualize the spatial distribution of predictive variables 

### ISSUE THREAD

**Issue by baiyissp112** [BIRD-TAO/CLCRN#2]
Thank you very much for opening your source code.

How can I visualize the spatial distribution of predictive variables like temperature.

like this picture
![image](https://user-images.githubusercontent.com/57715925/175853242-141a1462-aab1-402e-93b2-ae392a55e39a.png)

**Comment by EDAPINENUT** [comment]
First, the prediction and ground truth should be stored. After training, use `_get_time_prediction' function in Line 372 of https://github.com/BIRD-TAO/CLCRN/blob/main/supervisor.py to save them.
After the prediction and the ground truth are saved, you can use visualization tools, such as geoviews. For example, you can refer to https://www.kaggle.com/code/glarvor/dataviz-explore-meteonet-using-geoviews for more details.
