### ISSUE TITLE
Details about the used weather variables

### ISSUE THREAD

**Issue by jlidw** [BIRD-TAO/CLCRN#3]
Hi, thanks for your excellent work! 

When I checked the raw **WeatherBench** data, I found there were many vertical levels; but your AAAI paper just stated the "temperature, cloud cover, humidity and surface wind component".  So whether is the temperature '2m_temperature'? The wind is '10m_u_component_of_wind' and '10m_v_component_of_wind'? And how about the humidity? Is it 'Specific_humidity' or 'Relative_humidity'? Which level does it belong to?

Looking forward to your reply, thanks!

**Comment by EDAPINENUT** [comment]
Please refer to Line.227 to 237 in https://github.com/BIRD-TAO/CLCRN/blob/main/scripts/generate_training_data.py and the corresponding attribute names in WeatherBench for details.
